### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by WARDOGSK93** [WARDOGSK93/GumBalls#1]
### Deafult GumBalls
- [ ] Always Done Swiftly
- [ ] Arms Grace
- [ ] Coagulant
- [ ] In Plain Sight
- [ ] Stock Option

### Normal GumBalls
- [ ] Impatient
- [ ] Sword Flay
- [ ] Anywhere But Here
- [ ] Danger Close
- [ ] Armamental Accopmplishment
- [ ] Firing On All Cylinders
- [ ] Rsenal Acclerator
- [ ] Luck Crit
- [ ] Now You See Me
- [ ] Alchemical Antithesis

### Common GumBalls
- [ ] AfterTaste
- [ ] Burned Out
- [ ] Dead Or Nucler Winter
- [ ] Ephemerak Enhancement
- [ ] Im Feeling Lucky
- [ ] Immolation Liquidation
- [ ] Licended Contractor
- [ ] Phoenix Up
- [ ] Pop Shocks
- [ ] Respin Cycle
- [ ] Unquenchable
- [ ] Whos Keeping Score

### Rare GumBalls
- [ ] Cache Back
- [ ] Kill Joy
- [ ] On The House
- [ ] Wall Power

### Ultra Rare GumBalls
- [ ] Killing Time
- [x] Perk-A-Holic

**Comment by WARDOGSK93** [comment]
Locked until ported to World at War

**Comment by WARDOGSK93** [comment]
Unlocked due to the basic system being ported to World at War

**Comment by WARDOGSK93** [comment]
TODO list cleared due to restarting this

All perk based Gumballs complete

**Comment by MajorPwnege01** [comment]
**Custom Gumballs**
- [ ] StockUp - Spawns a random weapon - 2 activation's
- [ ] LicensedKiller - Makes weapons stronger for a limited time (5-6 minutes) - Activates immediately 
- [ ] Amelioration Liquidation- Spawns a bonfire sale power up - 1 activation

**Comment by WARDOGSK93** [comment]
**Update**
All powerup based Gumballs complete
